[package]
name = ""--- just a name of the file pretty sure in the github
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
warp = "imezx/warp@1.0.11"
Signal = "sleitnick/signal@^1"
TableUtil = "sleitnick/table-util@^1"
Trove = "sleitnick/trove@^1"
cmdr = "lipetos/cmdr@1.12.2"
spr = "blackjackiee/spr@1.1.3"
profileservice = "lipetos/profileservice@0.1.0"
behaviortree3 = "lipetos/behaviortree3@0.1.0"
simplepath = "lipetos/simplepath@0.1.2"