return {
    Health = {
        [1] = {
            Min = 700,
            Max = 2800,
        },

        [2] = {
            Min = 550,
            Max = 2200,
        },

        [3] = {
            Min = 367,
            Max = 1468,
        },

        [4] = {
            Min = 183,
            Max = 732,
        }
    },

    Attack = {
        [1] = {
            Min = 90,
            Max = 360,
        },

        [2] = {
            Min = 79,
            Max = 316,
        },

        [3] = {
            Min = 53,
            Max = 212,
        },

        [4] = {
            Min = 26,
            Max = 104,
        }
    },

    Defense = {
        [1] = {
            Min = 60,
            Max = 240,
        },

        [2] = {
            Min = 46,
            Max = 184,
        },

        [3] = {
            Min = 31,
            Max = 124,
        },

        [4] = {
            Min = 15,
            Max = 60,
        }
    },

    ["Health%"] = {
        [1] = {
            Min = 9,
            Max = 36,
        },

        [2] = {
            Min = 7.5,
            Max = 30,
        },

        [3] = {
            Min = 5,
            Max = 20,
        },

        [4] = {
            Min = 2.5,
            Max = 10,
        }
    },

    ["Attack%"] = {
        [1] = {
            Min = 9,
            Max = 36,
        },

        [2] = {
            Min = 7.5,
            Max = 30,
        },

        [3] = {
            Min = 5,
            Max = 20,
        },

        [4] = {
            Min = 2.5,
            Max = 10,
        }
    },

    ["Defense%"] = {
        [1] = {
            Min = 16,
            Max = 64,
        },

        [2] = {
            Min = 12,
            Max = 48,
        },

        [3] = {
            Min = 8,
            Max = 32,
        },

        [4] = {
            Min = 4,
            Max = 16,
        }
    },

    ["Daze%"] = {
        [1] = {
            Min = 6,
            Max = 24,
        },

        [2] = {
            Min = 4.5,
            Max = 18,
        },

        [3] = {
            Min = 3,
            Max = 12,
        },

        [4] = {
            Min = 1.5,
            Max = 6,
        }
    },

    Critical_Rate = {
        [1] = {
            Min = 8,
            Max = 32,
        },

        [2] = {
            Min = 6,
            Max = 24,
        },

        [3] = {
            Min = 4,
            Max = 16,
        },

        [4] = {
            Min = 2,
            Max = 8,
        }
    },

    Critical_Damage = {
        [1] = {
            Min = 16,
            Max = 64,
        },

        [2] = {
            Min = 12,
            Max = 48,
        },

        [3] = {
            Min = 8,
            Max = 32,
        },

        [4] = {
            Min = 4,
            Max = 16,
        }
    },

    Affliction_Aptitude = {
        [1] = {
            Min = 27,
            Max = 108,
        },

        [2] = {
            Min = 23,
            Max = 92,
        },

        [3] = {
            Min = 15,
            Max = 60,
        },

        [4] = {
            Min = 8,
            Max = 32,
        }
    },
}